title: Kebun Digital Eja
description: Tempat tumbuh pelan-pelan
baseurl: "rzpage"
url: "https://reizarahmadi.github.io"
collections:
  notes:
    output: true
defaults:
  - scope:
      path: "_posts"
    values:
      layout: default
      permalink: /:name/
